import { randomUUID } from 'node:crypto'

import bcrypt from 'bcryptjs'

import { encryptSecret } from '../lib/crypto.js'

type ParsedArgs = Record<string, string>

function printHelp() {
  console.log(`Usage:

Create customer + attach VPS:
  npm run generate:manual-sql --workspace @clawnow/api -- \\
    --business-name "Acme Sdn Bhd" \\
    --user-name "Jane Doe" \\
    --email "jane@example.com" \\
    --login-password "customer-login-password" \\
    --server-password "root-password" \\
    --server-ip "203.0.113.10" \\
    --hostname "vmi123.contaboserver.net" \\
    --server-name "Acme VPS" \\
    --instance-name "Acme OpenClaw"

Attach VPS to an existing account:
  npm run generate:manual-sql --workspace @clawnow/api -- \\
    --account-id "ACCOUNT_ID_HERE" \\
    --email "jane@example.com" \\
    --server-password "root-password" \\
    --server-ip "203.0.113.10" \\
    --hostname "vmi123.contaboserver.net" \\
    --server-name "Acme VPS" \\
    --instance-name "Acme OpenClaw"

Optional flags:
  --region SIN
  --provider-vm-id manual-contabo-...
  --cpu-millicores 4000
  --memory-mb 8192
  --disk-gb 200
`)
}

function parseArgs(argv: string[]): ParsedArgs {
  const parsed: ParsedArgs = {}

  for (let index = 0; index < argv.length; index += 1) {
    const token = argv[index]
    if (!token.startsWith('--')) continue

    const key = token.slice(2)
    const value = argv[index + 1]

    if (!value || value.startsWith('--')) {
      throw new Error(`Missing value for --${key}`)
    }

    parsed[key] = value
    index += 1
  }

  return parsed
}

function required(args: ParsedArgs, key: string) {
  const value = args[key]
  if (!value) {
    throw new Error(`Missing required argument --${key}`)
  }
  return value
}

function sqlString(value: string) {
  return `'${value.replaceAll("'", "''")}'`
}

async function main() {
  const argv = process.argv.slice(2)
  if (argv.includes('--help') || argv.includes('-h')) {
    printHelp()
    process.exit(0)
  }

  const args = parseArgs(argv)

  const existingAccountId = args['account-id']
  const email = required(args, 'email').toLowerCase()
  const region = args.region ?? 'SIN'
  const providerVmId = args['provider-vm-id'] ?? `manual-contabo-${randomUUID()}`
  const cpuMillicores = args['cpu-millicores'] ?? '4000'
  const memoryMb = args['memory-mb'] ?? '8192'
  const diskGb = args['disk-gb'] ?? '200'

  const serverPassword = required(args, 'server-password')
  const serverIp = required(args, 'server-ip')
  const hostname = required(args, 'hostname')
  const serverName = required(args, 'server-name')
  const instanceName = required(args, 'instance-name')

  const accountId = existingAccountId ?? randomUUID()
  const userId = existingAccountId ? null : randomUUID()
  const vmId = randomUUID()
  const instanceId = randomUUID()
  const eventId = randomUUID()

  const encryptedServerPassword = encryptSecret(serverPassword)
  const loginPasswordHash = existingAccountId
    ? null
    : await bcrypt.hash(required(args, 'login-password'), 12)
  const businessName = existingAccountId ? null : required(args, 'business-name')
  const userName = existingAccountId ? null : args['user-name'] ?? businessName

  const accountInsert = existingAccountId
    ? ''
    : `insert into "Account" (
  "id",
  "name",
  "createdAt",
  "updatedAt"
) values (
  ${sqlString(accountId)},
  ${sqlString(businessName!)},
  now(),
  now()
);

insert into "User" (
  "id",
  "accountId",
  "email",
  "passwordHash",
  "name",
  "createdAt",
  "updatedAt"
) values (
  ${sqlString(userId!)},
  ${sqlString(accountId)},
  ${sqlString(email)},
  ${sqlString(loginPasswordHash!)},
  ${sqlString(userName!)},
  now(),
  now()
);
`

  const sql = `-- Generated by apps/api/src/scripts/generate-manual-sql.ts
-- Email: ${email}
-- Account ID: ${accountId}
-- VM ID: ${vmId}
-- Instance ID: ${instanceId}
-- Event ID: ${eventId}
-- Provider VM ID: ${providerVmId}

begin;

${accountInsert}insert into "Vm" (
  "id",
  "provider",
  "providerVmId",
  "name",
  "hostname",
  "publicIp",
  "region",
  "sizeSlug",
  "cpuTotalMillicores",
  "reservedCpuMillicores",
  "memoryTotalMb",
  "reservedMemoryMb",
  "diskTotalGb",
  "containerCount",
  "maxInstances",
  "status",
  "createdAt",
  "updatedAt"
) values (
  ${sqlString(vmId)},
  'CONTABO'::"Provider",
  ${sqlString(providerVmId)},
  ${sqlString(serverName)},
  ${sqlString(hostname)},
  ${sqlString(serverIp)},
  ${sqlString(region)},
  'manual-contabo',
  ${cpuMillicores},
  0,
  ${memoryMb},
  0,
  ${diskGb},
  1,
  1,
  'ACTIVE'::"VmStatus",
  now(),
  now()
);

insert into "OpenClawInstance" (
  "id",
  "accountId",
  "currentVmId",
  "name",
  "imageTag",
  "sizeProfile",
  "reservedCpuMillicores",
  "reservedMemoryMb",
  "region",
  "state",
  "adminUsername",
  "sshPasswordCiphertext",
  "sshPasswordLastRotatedAt",
  "createdAt",
  "updatedAt"
) values (
  ${sqlString(instanceId)},
  ${sqlString(accountId)},
  ${sqlString(vmId)},
  ${sqlString(instanceName)},
  'manual-contabo',
  'SMALL'::"SizeProfile",
  0,
  0,
  ${sqlString(region)},
  'RUNNING'::"InstanceState",
  'root',
  ${sqlString(encryptedServerPassword)},
  now(),
  now(),
  now()
);

insert into "InstanceEvent" (
  "id",
  "instanceId",
  "type",
  "message",
  "metadata"
) values (
  ${sqlString(eventId)},
  ${sqlString(instanceId)},
  'manual.attach',
  'Manually attached Contabo VPS for seminar access',
  jsonb_build_object(
    'provider', 'contabo',
    'publicIp', ${sqlString(serverIp)},
    'username', 'root'
  )
);

commit;

select
  a.id as account_id,
  a.name as account_name,
  u.email,
  i.id as instance_id,
  i.name as instance_name,
  i.state,
  i."adminUsername",
  v.id as vm_id,
  v."publicIp",
  v.hostname,
  v.status as vm_status
from "Account" a
join "User" u on u."accountId" = a.id
left join "OpenClawInstance" i on i."accountId" = a.id
left join "Vm" v on v.id = i."currentVmId"
where lower(u.email) = lower(${sqlString(email)});
`

  console.log(sql)
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : String(error))
  printHelp()
  process.exit(1)
})
